from app.models.user import User
from app.models.role import Role, UserRole
from app.models.employee import Employee, EmployeeStatus
from app.models.project import Project
from app.models.material import Material
from app.models.material_type import MaterialType, MaterialTypeBrand
from app.models.supplier import Supplier
from app.models.attendance import Attendance
from app.models.inventory import Inventory
from app.models.transaction import Transaction
from app.models.quotation import Quotation
from app.models.setting import Setting
from app.models.company import Company
from app.models.calendar_day import CalendarDay
from app.models.billing import Billing
from app.models.commission import Commission, CommissionRate
from app.models.sow_type import SowType, SowTypeItem
# Must be registered here, not just imported by main.py: migrations/env.py
# only sees models imported through this package, and without this an
# autogenerated migration would include a DROP TABLE for the templates.
from app.models.quotation_template_item import QuotationTemplateItem
