"""add billing paid tracking

Revision ID: 20a6d4a40928
Revises: 5c1a2f20e744
Create Date: 2026-07-16 16:25:31.490165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '20a6d4a40928'
down_revision: Union[str, Sequence[str], None] = '5c1a2f20e744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billings', sa.Column('is_paid', sa.Boolean(), nullable=True))
    op.add_column('billings', sa.Column('paid_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###
    # Backfill existing rows — without this, ALTER TABLE leaves is_paid NULL for
    # pre-existing billings, which fails BillingRead's `is_paid: bool` validation.
    op.execute("UPDATE billings SET is_paid = 0 WHERE is_paid IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billings', 'paid_date')
    op.drop_column('billings', 'is_paid')
    # ### end Alembic commands ###
