"""add tip field to attendance

Revision ID: 39da0c033061
Revises: c8b127191713
Create Date: 2026-07-31 00:55:08.565753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39da0c033061'
down_revision: Union[str, Sequence[str], None] = 'c8b127191713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('tip', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'tip')
    # ### end Alembic commands ###
