"""add billing table

Revision ID: 5c1a2f20e744
Revises: 2262fd1ee262
Create Date: 2026-07-15 22:56:15.041075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5c1a2f20e744'
down_revision: Union[str, Sequence[str], None] = '2262fd1ee262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('billing_type', sa.String(length=20), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('billing_date', sa.Date(), nullable=False),
    sa.Column('current_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('previous_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('dp_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('retention_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('archived_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billings_id'), 'billings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_billings_id'), table_name='billings')
    op.drop_table('billings')
    # ### end Alembic commands ###
