"""add billing scope description and company letterhead fields

Revision ID: 93dad5f39c45
Revises: 20a6d4a40928
Create Date: 2026-07-16 17:58:18.033322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '93dad5f39c45'
down_revision: Union[str, Sequence[str], None] = '20a6d4a40928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billings', sa.Column('scope_description', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('pcab_license', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('signature_url', sa.Text(), nullable=True))
    op.alter_column('companies', 'logo_url',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'logo_url',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('companies', 'signature_url')
    op.drop_column('companies', 'pcab_license')
    op.drop_column('billings', 'scope_description')
    # ### end Alembic commands ###
