"""initial schema

Revision ID: f0de4b7effeb
Revises: 
Create Date: 2026-06-01 15:18:58.769655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0de4b7effeb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_index(op.f('ix_calendar_days_id'), 'calendar_days', ['id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('contact_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('footer_text', sa.String(length=500), nullable=True),
    sa.Column('default_signatory', sa.String(length=100), nullable=True),
    sa.Column('signatory_position', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('date_hired', sa.Date(), nullable=True),
    sa.Column('daily_salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sss_number', sa.String(length=50), nullable=True),
    sa.Column('philhealth_number', sa.String(length=50), nullable=True),
    sa.Column('pagibig_number', sa.String(length=50), nullable=True),
    sa.Column('tin_number', sa.String(length=50), nullable=True),
    sa.Column('emergency_contact', sa.String(length=100), nullable=True),
    sa.Column('emergency_phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Resigned', 'Terminated', name='employeestatus'), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_table('material_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_material_types_id'), 'material_types', ['id'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating_size', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('material_type', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_company_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('project_manager', sa.String(length=100), nullable=True),
    sa.Column('quotation_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('referred_by', sa.String(length=100), nullable=True),
    sa.Column('lgu', sa.String(length=100), nullable=True),
    sa.Column('meralco_branch', sa.String(length=100), nullable=True),
    sa.Column('contract_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('encumbrance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('other_notes', sa.String(length=1000), nullable=True),
    sa.Column('scope_wiring_permit', sa.Boolean(), nullable=True),
    sa.Column('scope_wiring_permit_status', sa.String(length=50), nullable=True),
    sa.Column('scope_wiring_permit_date', sa.Date(), nullable=True),
    sa.Column('scope_wiring_permit_notes', sa.String(length=500), nullable=True),
    sa.Column('scope_electrical_plan', sa.Boolean(), nullable=True),
    sa.Column('scope_electrical_plan_status', sa.String(length=50), nullable=True),
    sa.Column('scope_electrical_plan_date', sa.Date(), nullable=True),
    sa.Column('scope_electrical_plan_notes', sa.String(length=500), nullable=True),
    sa.Column('scope_installation', sa.Boolean(), nullable=True),
    sa.Column('scope_installation_status', sa.String(length=50), nullable=True),
    sa.Column('scope_installation_date', sa.Date(), nullable=True),
    sa.Column('scope_installation_notes', sa.String(length=500), nullable=True),
    sa.Column('scope_cfei', sa.Boolean(), nullable=True),
    sa.Column('scope_cfei_status', sa.String(length=50), nullable=True),
    sa.Column('scope_cfei_date', sa.Date(), nullable=True),
    sa.Column('scope_cfei_notes', sa.String(length=500), nullable=True),
    sa.Column('scope_supply', sa.Boolean(), nullable=True),
    sa.Column('scope_supply_status', sa.String(length=50), nullable=True),
    sa.Column('scope_supply_date', sa.Date(), nullable=True),
    sa.Column('scope_supply_notes', sa.String(length=500), nullable=True),
    sa.Column('scope_meralco', sa.Boolean(), nullable=True),
    sa.Column('scope_meralco_status', sa.String(length=50), nullable=True),
    sa.Column('scope_meralco_date', sa.Date(), nullable=True),
    sa.Column('scope_meralco_notes', sa.String(length=500), nullable=True),
    sa.Column('scope_others', sa.Boolean(), nullable=True),
    sa.Column('scope_others_text', sa.String(length=500), nullable=True),
    sa.Column('scope_others_status', sa.String(length=50), nullable=True),
    sa.Column('scope_others_date', sa.Date(), nullable=True),
    sa.Column('scope_others_notes', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('quotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('template_type', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_logo_url', sa.String(length=500), nullable=True),
    sa.Column('company_address', sa.String(length=255), nullable=True),
    sa.Column('company_contact', sa.String(length=100), nullable=True),
    sa.Column('company_footer', sa.String(length=500), nullable=True),
    sa.Column('addressee_name', sa.String(length=255), nullable=True),
    sa.Column('addressee_address', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('quotation_date', sa.Date(), nullable=True),
    sa.Column('signatory_name', sa.String(length=100), nullable=True),
    sa.Column('signatory_title', sa.String(length=100), nullable=True),
    sa.Column('project_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estimated_savings', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('roi', sa.String(length=100), nullable=True),
    sa.Column('system_size_kwp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('inverter_brand', sa.String(length=100), nullable=True),
    sa.Column('battery_brand', sa.String(length=100), nullable=True),
    sa.Column('panel_brand', sa.String(length=100), nullable=True),
    sa.Column('scope_of_works', sa.String(length=2000), nullable=True),
    sa.Column('terms_of_payment', sa.String(length=2000), nullable=True),
    sa.Column('bill_of_materials', sa.JSON(), nullable=True),
    sa.Column('other_scope_costs', sa.JSON(), nullable=True),
    sa.Column('mode_of_payment', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('exclusions', sa.String(length=2000), nullable=True),
    sa.Column('total_contract_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotations_id'), 'quotations', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_number', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('employee_name', sa.String(length=255), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('is_office_based', sa.Boolean(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('regular_time_in', sa.String(length=10), nullable=True),
    sa.Column('regular_time_out', sa.String(length=10), nullable=True),
    sa.Column('regular_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overtime_time_in', sa.String(length=10), nullable=True),
    sa.Column('overtime_time_out', sa.String(length=10), nullable=True),
    sa.Column('overtime_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overtime_multiplier', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('regular_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('overtime_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('latest_unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_id'), 'inventory', ['id'], unique=False)
    op.create_table('material_type_brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_type_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['material_type_id'], ['material_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_type_brands_id'), 'material_type_brands', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=100), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('is_office_expense', sa.Boolean(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('expenditure_category', sa.String(length=100), nullable=True),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('materials', sa.JSON(), nullable=True),
    sa.Column('use_fifo_pricing', sa.Boolean(), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('adjustment_direction', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('invite_token', sa.String(length=255), nullable=True),
    sa.Column('invite_token_expires', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_material_type_brands_id'), table_name='material_type_brands')
    op.drop_table('material_type_brands')
    op.drop_index(op.f('ix_inventory_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_quotations_id'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_material_types_id'), table_name='material_types')
    op.drop_table('material_types')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_calendar_days_id'), table_name='calendar_days')
    op.drop_table('calendar_days')
    # ### end Alembic commands ###
